config/routes.rb
HagitJobs::Application.routes.draw do
  resources :hours

  resources :jobs

  get "home/index"

  root :to => 'home#index'

end

app/models/hour.rb
class Hour < ActiveRecord::Base
  attr_accessible :amount, :date, :job
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :add_hour_per, :description, :job, :pay_per_hour
    validates :job, :presence=> true, :uniqueness=> true
    
    has_many :hours
end

app/models/jobs.rb
class Jobs < ActiveRecord::Base
  attr_accessible :description, :jobs, :pay_per_hour
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hours }
    end
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
    @hour = Hour.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/new
  # GET /hours/new.json
  def new
    @hour = Hour.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/1/edit
  def edit
    @hour = Hour.find(params[:id])
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(params[:hour])

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render json: @hour, status: :created, location: @hour }
      else
        format.html { render action: "new" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hours/1
  # PUT /hours/1.json
  def update
    @hour = Hour.find(params[:id])

    respond_to do |format|
      if @hour.update_attributes(params[:hour])
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour = Hour.find(params[:id])
    @hour.destroy

    respond_to do |format|
      format.html { redirect_to hours_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/index.html.erb
<h1><center>Hagit's Jobs</center></h1>
<%= link_to "Jobs", jobs_path %>
<br />
<%= link_to "Hours", hours_path %>
<br />


<footer><p>Find me in app/views/home/index.html.erb</p></footer>

app/views/hours/_form.html.erb
<%= form_for(@hour) do |f| %>
  <% if @hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
      <% @hour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hours/edit.html.erb
<h1>Editing hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @hour %> |
<%= link_to 'Back', hours_path %>

app/views/hours/index.html.erb
<h1>Listing hours</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Job</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hours.each do |hour| %>
  <tr>
    <td><%= hour.date %></td>
    <td><%= hour.job %></td>
    <td><%= hour.amount %></td>
    <td><%= link_to 'Show', hour %></td>
    <td><%= link_to 'Edit', edit_hour_path(hour) %></td>
    <td><%= link_to 'Destroy', hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hour', new_hour_path %>
<%= link_to 'Home', root_path %>

app/views/hours/new.html.erb
<h1>New hour</h1>

<%= render 'form' %>

<%= link_to 'Back', hours_path %>

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @hour.date %>
</p>

<p>
  <b>Job:</b>
  <%= @hour.job %>
</p>

<p>
  <b>Amount:</b>
  <%= @hour.amount %>
</p>


<%= link_to 'Edit', edit_hour_path(@hour) %> |
<%= link_to 'Back', hours_path %>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :pay_per_hour %><br />
    <%= f.text_field :pay_per_hour %>
  </div>
  <div class="field">
    <%= f.label :add_hour_per %><br />
    <%= f.text_field :add_hour_per %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1><center>Listing jobs</center></h1>

<table>
  <tr>
    <th>Job</th>
    <th>Pay per hour</th>
    <th>Add hour per</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.job %></td>
    <td><%= job.pay_per_hour %></td>
    <td><%= job.add_hour_per %></td>
    <td><%= job.description %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %><br />
<%= link_to "Home", root_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Job:</b>
  <%= @job.job %>
</p>

<p>
  <b>Pay per hour:</b>
  <%= @job.pay_per_hour %>
</p>

<p>
  <b>Add hour per:</b>
  <%= @job.add_hour_per %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HagitJobs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>